//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day4_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aboutCountry
    {
        public string Code { get; set; }
        public string Country { get; set; }
        public string img { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> timecreate { get; set; }
    }
}
