create database travel
go
use travel
go

create table aboutCountry
(
	Code varchar(10) primary key,
	Country nvarchar(30),
	img varchar(100),
	[Description] nvarchar(max),
	timecreate datetime
)

insert into aboutCountry values
('vi',N'Việt Nam','/Content/images/vietnam.png',N'Du lịch Việt Nam được Nhà nước Việt Nam xem là một ngành kinh tế mũi nhọn vì cho rằng đất nước Việt Nam có tiềm năng du lịch đa dạng và phong phú. Năm 2019, ngành Du lịch Việt Nam lập kỳ tích lần đầu tiên đón 18 triệu lượt khách quốc tế, tăng 16,2% so với năm 2018. Giai đoạn từ 2015-2019, lượng khách quốc tế đến Việt Nam đã tăng 2,3 lần từ 7,9 triệu lượt lên 18 triệu lượt, tốc độ tăng trưởng bình quân đạt 22,7% mỗi năm. Việt Nam liên tục nằm trong nhóm những quốc gia có tốc độ tăng trưởng khách du lịch nhanh nhất thế giới. Năm 2019, du lịch Việt Nam nhận giải thưởng Điểm đến di sản hàng đầu thế giới do World Travel Awards trao tặng, Điểm đến Golf tốt nhất thế giới do World Golf Awards trao tặng. Cùng với đó, World Travel Awards cũng vinh danh Việt Nam là Điểm đến hàng đầu châu Á 2 năm liên tiếp 2018-2019, Điểm đến văn hóa hàng đầu châu Á 2019, Điểm đến ẩm thực hàng đầu châu Á 2019.[2]Tuy nhiên, ngành du lịch Việt Nam có những hạn chế như tỷ lệ khách quay trở lại thấp (10-40%). Chi tiêu của khách du lịch quốc tế tại Việt Nam không cao, trung bình hơn 1.000 USD cho một chuyến 9 ngày do sản phẩm du lịch của Việt Nam chưa hấp dẫn, thiếu gắn kết, các hoạt động giải trí, mua sắm, chăm sóc khách chưa đa dạng, công tác xúc tiến quảng bá chưa thực sự hiệu quả do hạn chế về nguồn lực, cơ chế vận hành, chưa thành lập Văn phòng xúc tiến du lịch ở nước ngoài, Quỹ hỗ trợ và phát triển du lịch chưa được vận hành và đi vào hoạt động; hạ tầng sân bay có xu hướng quá tải, chưa đáp ứng được tốc độ tăng trưởng cao về số lượng khách du lịch; chính sách thị thực nhập cảnh còn hạn chế so với các điểm đến cạnh tranh trực tiếp của du lịch Việt Nam như Thái Lan.',GETDATE()),
('us',N'Mỹ','/Content/images/US.png',N'Theo nhân viên tư vấn tour Mỹ tại Vietravel, thủ tục xin visa Mỹ vẫn không có gì thay đổi và mọi du khách đều có cơ hội như nhau. Hiện nay có khoảng 150 du khách đăng ký tour Mỹ và đang chờ lịch hẹn phỏng vấn. Lịch hẹn phỏng vấn tại TP HCM vào tháng 9-2022, còn tại Hà Nội vào tháng 8-2022 và kết quả sẽ được viên chức lãnh sự trả lời ngay khi kết thúc phỏng vấn. Nếu du khách được chấp thuận visa thì lãnh sự quán sẽ chuyển hộ chiếu có dán visa về Công ty Vietravel trong vòng 3-7 ngày làm việc. Ngoài ra, lời khuyên hữu ích dành cho du khách là nên đăng ký tour Mỹ trước ngày khởi hành ít nhất 3 tháng để bảo đảm đạt visa và không ảnh hưởng đến kế hoạch của du khách.', GETDATE()),
('jp',N'Nhật Bản','/Content/images/japan.png',N'Ông Yoshida Kenji, Trưởng đại diện, JNTO tại Việt Nam cho biết, sẽ có rất nhiều hoạt động quảng bá được thực hiện nhân dịp này vì đây không chỉ là hoạt động mở lại du lịch Nhật Bản mà đây còn là dịp “Kỷ niệm 50 năm thiết lập quan hệ ngoại giao Nhật Bản – Việt Nam” kể từ tháng 1/2023. Trước đó, từ ngày 5-10/8, Vietnam Airlines đã tổ chức Famtrip dành cho các công ty lữ hành khảo sát du lịch Nhật Bản. Đây là chuyến Famtrip đầu tiên tới Nhật Bản kể từ khi dịch Covid-19 bùng phát. JNTO Việt Nam đã phối hợp cùng Japan Shopping Tourism Organization (JSTO) tổ chức tiệc chào đón đoàn Famtrip tại Tokyo và Osaka',GETDATE()),
('kr',N'Hàn Quốc','/Content/images/korea.png',N'Với việc bỏ yêu cầu xét nghiệm COVID-19 sau khi nhập cảnh, du khách đến với Hàn Quốc sẽ chỉ cần điền thông tin nhập cảnh tại trang web Q-code và nhận mã Q-Code để trình tại sân bay khi làm thủ tục nhập cảnh. Hàn Quốc cũng không yêu cầu du khách khai báo thông tin số mũi tiêm vaccine COVID-19 khi điền thông tin nhập cảnh. Để thuận tiện cho việc khai thông tin trên hệ thống Q-code đối với du khách Việt Nam, từ ngày 22/8/2022, Hàn Quốc cũng đã triển khai phiên bản tiếng Việt trên trang đăng ký thông tin này. Du khách có thể vào hệ thống Q-Code và lựa chọn tiếng Việt để khai báo dễ dàng.',GETDATE()),
('th',N'Thái Lan','/Content/images/thail.png',N'Với việc bỏ yêu cầu xét nghiệm COVID-19 sau khi nhập cảnh, du khách đến với Hàn Quốc sẽ chỉ cần điền thông tin nhập cảnh tại trang web Q-code và nhận mã Q-Code để trình tại sân bay khi làm thủ tục nhập cảnh. Hàn Quốc cũng không yêu cầu du khách khai báo thông tin số mũi tiêm vaccine COVID-19 khi điền thông tin nhập cảnh. Để thuận tiện cho việc khai thông tin trên hệ thống Q-code đối với du khách Việt Nam, từ ngày 22/8/2022, Hàn Quốc cũng đã triển khai phiên bản tiếng Việt trên trang đăng ký thông tin này. Du khách có thể vào hệ thống Q-Code và lựa chọn tiếng Việt để khai báo dễ dàng.',GETDATE()),
('ru',N'Nga','/Content/images/rusia.png',N'Với việc bỏ yêu cầu xét nghiệm COVID-19 sau khi nhập cảnh, du khách đến với Hàn Quốc sẽ chỉ cần điền thông tin nhập cảnh tại trang web Q-code và nhận mã Q-Code để trình tại sân bay khi làm thủ tục nhập cảnh. Hàn Quốc cũng không yêu cầu du khách khai báo thông tin số mũi tiêm vaccine COVID-19 khi điền thông tin nhập cảnh. Để thuận tiện cho việc khai thông tin trên hệ thống Q-code đối với du khách Việt Nam, từ ngày 22/8/2022, Hàn Quốc cũng đã triển khai phiên bản tiếng Việt trên trang đăng ký thông tin này. Du khách có thể vào hệ thống Q-Code và lựa chọn tiếng Việt để khai báo dễ dàng.',GETDATE())

